# 应用服务 WEB 访问端口
server:
 port: 8082

dubbo:
 application:
  name: javert-dubbo-consumer
 registry:
  address: zookeeper://172.22.0.44:2181
 protocol:
  name: dubbo
  port: 20880
 consumer:
  timemout: 5000
